# Generated by Django 2.2.5 on 2019-09-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=128, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoCivil', models.CharField(max_length=128, verbose_name='Estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=128, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotacao', models.CharField(max_length=128, verbose_name='Lotacao')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=128, verbose_name='Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=128, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=128, verbose_name='Nome do Funcionário')),
                ('data_de_nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('matricula', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Matricula')),
                ('telefone_celular', models.CharField(help_text='Número do telefone celular no formato (99) 99999-9999', max_length=15, unique=True, verbose_name='Telefone celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_editable', models.BooleanField(verbose_name='Editavel?')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Cargo', verbose_name='Cargo do funcionario')),
                ('estadoCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.EstadoCivil', verbose_name='Estado Civil')),
                ('estadoNascimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Estados', verbose_name='Estado de nascimento')),
                ('lotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Lotacao', verbose_name='Departamento que o Funcionario está lotado')),
                ('municipioNascimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Municipio', verbose_name='Municipio de nascimento')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Sexo', verbose_name='Sexo')),
            ],
        ),
    ]
